### PR TITLE
Ubuntu1904

### PR DESCRIPTION
**Pull request by danialbehzadi**
Update python deps to work on ubuntu 19.04

### CODE REVIEW

**Comment by ilius** [comment]
This will not work with older versions of python3-gi
You need to try importing both Glib and Gobject

**Comment by ilius** [comment]
And please checkout fa.mo
You have not changed fa.po

**Comment by ilius** [comment]
Please add another PR to next branch. I will be releasing 3.1.0 soon based on next branch

**Comment by danialbehzadi** [comment]
> Please checkout fa.mo
> You have not changed fa.po

The mo file updated automatically on install.

**Comment by ilius** [comment]
Yes, but you added it with git
Don't use git add -A

**Pull request closed without merging**
